//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ProtocolID.proto
namespace ProtocolID
{
    [global::ProtoBuf.ProtoContract(Name=@"ClientMsgID")]
    public enum ClientMsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_CHOOSE_SERVER_REQ", Value=10000)]
      CLIENT_MSG_CHOOSE_SERVER_REQ = 10000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_LOGIN_REQ", Value=10001)]
      CLIENT_MSG_LOGIN_REQ = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_HEARTBEAT", Value=10002)]
      CLIENT_MSG_HEARTBEAT = 10002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_MOVEO", Value=10100)]
      CLIENT_MSG_MOVEO = 10100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CLIENT_MSG_CAST_ABILITY_REQ", Value=10200)]
      CLIENT_MSG_CAST_ABILITY_REQ = 10200
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ServerMsgID")]
    public enum ServerMsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_MSG_CHOOSE_SERVER_ASK", Value=50000)]
      SERVER_MSG_CHOOSE_SERVER_ASK = 50000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVER_MSG_LOGIN_RES_ASK", Value=50001)]
      SERVER_MSG_LOGIN_RES_ASK = 50001
    }
  
}