// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/map_proto2_unittest.proto

#ifndef PROTOBUF_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_unittest {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();

class TestEnumMap;
class TestEnumMapPlusExtra;
class TestEnumStartWithNonZeroMap;

enum Proto2MapEnum {
  PROTO2_MAP_ENUM_FOO = 0,
  PROTO2_MAP_ENUM_BAR = 1,
  PROTO2_MAP_ENUM_BAZ = 2
};
bool Proto2MapEnum_IsValid(int value);
const Proto2MapEnum Proto2MapEnum_MIN = PROTO2_MAP_ENUM_FOO;
const Proto2MapEnum Proto2MapEnum_MAX = PROTO2_MAP_ENUM_BAZ;
const int Proto2MapEnum_ARRAYSIZE = Proto2MapEnum_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto2MapEnum_descriptor();
inline const ::std::string& Proto2MapEnum_Name(Proto2MapEnum value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto2MapEnum_descriptor(), value);
}
inline bool Proto2MapEnum_Parse(
    const ::std::string& name, Proto2MapEnum* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto2MapEnum>(
    Proto2MapEnum_descriptor(), name, value);
}
enum Proto2MapEnumPlusExtra {
  E_PROTO2_MAP_ENUM_FOO = 0,
  E_PROTO2_MAP_ENUM_BAR = 1,
  E_PROTO2_MAP_ENUM_BAZ = 2,
  E_PROTO2_MAP_ENUM_EXTRA = 3
};
bool Proto2MapEnumPlusExtra_IsValid(int value);
const Proto2MapEnumPlusExtra Proto2MapEnumPlusExtra_MIN = E_PROTO2_MAP_ENUM_FOO;
const Proto2MapEnumPlusExtra Proto2MapEnumPlusExtra_MAX = E_PROTO2_MAP_ENUM_EXTRA;
const int Proto2MapEnumPlusExtra_ARRAYSIZE = Proto2MapEnumPlusExtra_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto2MapEnumPlusExtra_descriptor();
inline const ::std::string& Proto2MapEnumPlusExtra_Name(Proto2MapEnumPlusExtra value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto2MapEnumPlusExtra_descriptor(), value);
}
inline bool Proto2MapEnumPlusExtra_Parse(
    const ::std::string& name, Proto2MapEnumPlusExtra* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto2MapEnumPlusExtra>(
    Proto2MapEnumPlusExtra_descriptor(), name, value);
}
enum Proto2MapEnumStartWithNonZero {
  PROTO2_NON_ZERO_MAP_ENUM_FOO = 1
};
bool Proto2MapEnumStartWithNonZero_IsValid(int value);
const Proto2MapEnumStartWithNonZero Proto2MapEnumStartWithNonZero_MIN = PROTO2_NON_ZERO_MAP_ENUM_FOO;
const Proto2MapEnumStartWithNonZero Proto2MapEnumStartWithNonZero_MAX = PROTO2_NON_ZERO_MAP_ENUM_FOO;
const int Proto2MapEnumStartWithNonZero_ARRAYSIZE = Proto2MapEnumStartWithNonZero_MAX + 1;

const ::google::protobuf::EnumDescriptor* Proto2MapEnumStartWithNonZero_descriptor();
inline const ::std::string& Proto2MapEnumStartWithNonZero_Name(Proto2MapEnumStartWithNonZero value) {
  return ::google::protobuf::internal::NameOfEnum(
    Proto2MapEnumStartWithNonZero_descriptor(), value);
}
inline bool Proto2MapEnumStartWithNonZero_Parse(
    const ::std::string& name, Proto2MapEnumStartWithNonZero* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Proto2MapEnumStartWithNonZero>(
    Proto2MapEnumStartWithNonZero_descriptor(), name, value);
}
// ===================================================================

class TestEnumMap : public ::google::protobuf::Message {
 public:
  TestEnumMap();
  virtual ~TestEnumMap();

  TestEnumMap(const TestEnumMap& from);

  inline TestEnumMap& operator=(const TestEnumMap& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestEnumMap& default_instance();

  void Swap(TestEnumMap* other);

  // implements Message ----------------------------------------------

  inline TestEnumMap* New() const { return New(NULL); }

  TestEnumMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestEnumMap& from);
  void MergeFrom(const TestEnumMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestEnumMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .protobuf_unittest.Proto2MapEnum> known_map_field = 101;
  int known_map_field_size() const;
  void clear_known_map_field();
  static const int kKnownMapFieldFieldNumber = 101;
  const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >&
      known_map_field() const;
  ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >*
      mutable_known_map_field();

  // map<int32, .protobuf_unittest.Proto2MapEnum> unknown_map_field = 102;
  int unknown_map_field_size() const;
  void clear_unknown_map_field();
  static const int kUnknownMapFieldFieldNumber = 102;
  const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >&
      unknown_map_field() const;
  ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >*
      mutable_unknown_map_field();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestEnumMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, Proto2MapEnum,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 >
      TestEnumMap_KnownMapFieldEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, Proto2MapEnum,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > known_map_field_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, Proto2MapEnum,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 >
      TestEnumMap_UnknownMapFieldEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, Proto2MapEnum,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > unknown_map_field_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestEnumMap* default_instance_;
};
// -------------------------------------------------------------------

class TestEnumMapPlusExtra : public ::google::protobuf::Message {
 public:
  TestEnumMapPlusExtra();
  virtual ~TestEnumMapPlusExtra();

  TestEnumMapPlusExtra(const TestEnumMapPlusExtra& from);

  inline TestEnumMapPlusExtra& operator=(const TestEnumMapPlusExtra& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestEnumMapPlusExtra& default_instance();

  void Swap(TestEnumMapPlusExtra* other);

  // implements Message ----------------------------------------------

  inline TestEnumMapPlusExtra* New() const { return New(NULL); }

  TestEnumMapPlusExtra* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestEnumMapPlusExtra& from);
  void MergeFrom(const TestEnumMapPlusExtra& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestEnumMapPlusExtra* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .protobuf_unittest.Proto2MapEnumPlusExtra> known_map_field = 101;
  int known_map_field_size() const;
  void clear_known_map_field();
  static const int kKnownMapFieldFieldNumber = 101;
  const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >&
      known_map_field() const;
  ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >*
      mutable_known_map_field();

  // map<int32, .protobuf_unittest.Proto2MapEnumPlusExtra> unknown_map_field = 102;
  int unknown_map_field_size() const;
  void clear_unknown_map_field();
  static const int kUnknownMapFieldFieldNumber = 102;
  const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >&
      unknown_map_field() const;
  ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >*
      mutable_unknown_map_field();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestEnumMapPlusExtra)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, Proto2MapEnumPlusExtra,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 >
      TestEnumMapPlusExtra_KnownMapFieldEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, Proto2MapEnumPlusExtra,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > known_map_field_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, Proto2MapEnumPlusExtra,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 >
      TestEnumMapPlusExtra_UnknownMapFieldEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, Proto2MapEnumPlusExtra,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      0 > unknown_map_field_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestEnumMapPlusExtra* default_instance_;
};
// -------------------------------------------------------------------

class TestEnumStartWithNonZeroMap : public ::google::protobuf::Message {
 public:
  TestEnumStartWithNonZeroMap();
  virtual ~TestEnumStartWithNonZeroMap();

  TestEnumStartWithNonZeroMap(const TestEnumStartWithNonZeroMap& from);

  inline TestEnumStartWithNonZeroMap& operator=(const TestEnumStartWithNonZeroMap& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestEnumStartWithNonZeroMap& default_instance();

  void Swap(TestEnumStartWithNonZeroMap* other);

  // implements Message ----------------------------------------------

  inline TestEnumStartWithNonZeroMap* New() const { return New(NULL); }

  TestEnumStartWithNonZeroMap* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestEnumStartWithNonZeroMap& from);
  void MergeFrom(const TestEnumStartWithNonZeroMap& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(TestEnumStartWithNonZeroMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<int32, .protobuf_unittest.Proto2MapEnumStartWithNonZero> map_field = 101;
  int map_field_size() const;
  void clear_map_field();
  static const int kMapFieldFieldNumber = 101;
  const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumStartWithNonZero >&
      map_field() const;
  ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumStartWithNonZero >*
      mutable_map_field();

  // @@protoc_insertion_point(class_scope:protobuf_unittest.TestEnumStartWithNonZeroMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::google::protobuf::int32, Proto2MapEnumStartWithNonZero,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      1 >
      TestEnumStartWithNonZeroMap_MapFieldEntry;
  ::google::protobuf::internal::MapField<
      ::google::protobuf::int32, Proto2MapEnumStartWithNonZero,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_ENUM,
      1 > map_field_;
  friend void  protobuf_AddDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
  friend void protobuf_AssignDesc_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto();

  void InitAsDefaultInstance();
  static TestEnumStartWithNonZeroMap* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// TestEnumMap

// map<int32, .protobuf_unittest.Proto2MapEnum> known_map_field = 101;
inline int TestEnumMap::known_map_field_size() const {
  return known_map_field_.size();
}
inline void TestEnumMap::clear_known_map_field() {
  known_map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >&
TestEnumMap::known_map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestEnumMap.known_map_field)
  return known_map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >*
TestEnumMap::mutable_known_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestEnumMap.known_map_field)
  return known_map_field_.MutableMap();
}

// map<int32, .protobuf_unittest.Proto2MapEnum> unknown_map_field = 102;
inline int TestEnumMap::unknown_map_field_size() const {
  return unknown_map_field_.size();
}
inline void TestEnumMap::clear_unknown_map_field() {
  unknown_map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >&
TestEnumMap::unknown_map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestEnumMap.unknown_map_field)
  return unknown_map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnum >*
TestEnumMap::mutable_unknown_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestEnumMap.unknown_map_field)
  return unknown_map_field_.MutableMap();
}

// -------------------------------------------------------------------

// TestEnumMapPlusExtra

// map<int32, .protobuf_unittest.Proto2MapEnumPlusExtra> known_map_field = 101;
inline int TestEnumMapPlusExtra::known_map_field_size() const {
  return known_map_field_.size();
}
inline void TestEnumMapPlusExtra::clear_known_map_field() {
  known_map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >&
TestEnumMapPlusExtra::known_map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestEnumMapPlusExtra.known_map_field)
  return known_map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >*
TestEnumMapPlusExtra::mutable_known_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestEnumMapPlusExtra.known_map_field)
  return known_map_field_.MutableMap();
}

// map<int32, .protobuf_unittest.Proto2MapEnumPlusExtra> unknown_map_field = 102;
inline int TestEnumMapPlusExtra::unknown_map_field_size() const {
  return unknown_map_field_.size();
}
inline void TestEnumMapPlusExtra::clear_unknown_map_field() {
  unknown_map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >&
TestEnumMapPlusExtra::unknown_map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestEnumMapPlusExtra.unknown_map_field)
  return unknown_map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumPlusExtra >*
TestEnumMapPlusExtra::mutable_unknown_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestEnumMapPlusExtra.unknown_map_field)
  return unknown_map_field_.MutableMap();
}

// -------------------------------------------------------------------

// TestEnumStartWithNonZeroMap

// map<int32, .protobuf_unittest.Proto2MapEnumStartWithNonZero> map_field = 101;
inline int TestEnumStartWithNonZeroMap::map_field_size() const {
  return map_field_.size();
}
inline void TestEnumStartWithNonZeroMap::clear_map_field() {
  map_field_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumStartWithNonZero >&
TestEnumStartWithNonZeroMap::map_field() const {
  // @@protoc_insertion_point(field_map:protobuf_unittest.TestEnumStartWithNonZeroMap.map_field)
  return map_field_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, Proto2MapEnumStartWithNonZero >*
TestEnumStartWithNonZeroMap::mutable_map_field() {
  // @@protoc_insertion_point(field_mutable_map:protobuf_unittest.TestEnumStartWithNonZeroMap.map_field)
  return map_field_.MutableMap();
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf_unittest

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::protobuf_unittest::Proto2MapEnum> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf_unittest::Proto2MapEnum>() {
  return ::protobuf_unittest::Proto2MapEnum_descriptor();
}
template <> struct is_proto_enum< ::protobuf_unittest::Proto2MapEnumPlusExtra> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf_unittest::Proto2MapEnumPlusExtra>() {
  return ::protobuf_unittest::Proto2MapEnumPlusExtra_descriptor();
}
template <> struct is_proto_enum< ::protobuf_unittest::Proto2MapEnumStartWithNonZero> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf_unittest::Proto2MapEnumStartWithNonZero>() {
  return ::protobuf_unittest::Proto2MapEnumStartWithNonZero_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2fmap_5fproto2_5funittest_2eproto__INCLUDED
